### PR TITLE
fix invite tests when device has public ipv6 address

### PR DESCRIPTION
**Pull request by dominictarr**
I think this should get things passing for you @mixmix can you run the tests on this branch?

### CODE REVIEW

**Comment by dominictarr** [comment]
you might need https://github.com/ssbc/ssb-config/pull/25 too

**Comment by mixmix** [comment]
can confirm this passes all test : 
- by itself
- with  ssbc/ssb-config#25

**Comment by mixmix** [comment]
Back on the wifi at home:
- :x: by itself
- :heavy_check_mark: with ssbc/ssb-config#25

**Comment by dominictarr** [comment]
cool. I didn't expect this to run on it's own on your weird home setup mix

**Comment by dominictarr** [comment]
touche

**Comment by dominictarr** [comment]
I have merged this into 13.6.1 (also depending on ssb-config@3) since it's just a fix.

**Pull request merged**
