### PR TITLE
Remove hack and fix blobs.add on cli

### PR DESCRIPTION
**Pull request by regular**
Update ssb-client to 4.5.0 and removes the blobs.add hack (which is part of ssb-client since ssb-client@4.5.0)

### CODE REVIEW

**Comment by regular** [comment]
Hmm ... this seems to make the tests hang forever

**Comment by dominictarr** [comment]
thats a manifest problem. I think the manifest needs to be set on the client to include createHistoryStream

**Comment by dominictarr** [comment]
btw, which test hangs? some of them do take a while, normally if it's test/random.js it's already, although test/blob* is pretty good at hanging too

**Comment by regular** [comment]
"# test invite with note" is the last one that is started.
```
ok 17 should be equivalent
```
is the last assertion before it hangs.

**Comment by christianbundy** [comment]
@regular Is this still something that you'd like to see merged?

**Comment by regular** [comment]
@christianbundy on one hand, it's not good that we have workarounds in two separate places for the same issue. On the other hand, things evolved a bit since I opened this, so it would require some more work and I currently don't have the capacity to deal with this. I had lots of issues with blobs.add on the command line in the past, it would error every now and then and not add the blob (2/3 chance of success roughly) I guess that's related but haven't tracked it down.

**Comment by dominictarr** [comment]
btw: it would be cool to fix this in muxrpc - so that sink streams could callback a value (would also mean a strong confirmation that the stream succeeded) I'd estimate the effort there as a day or two. but the only thing that needs that is `blobs.add` so it's a lot of work for little reward. Better to leave it until a new version of muxrpc. (I did try to write one last southern summer , and it was working, but deploying it screwed up everything because I hadn't implemented back pressure well (the infamous muxrpc@7)- iirc I did consider supporting this case though)

**Comment by regular** [comment]
@dominictarr I am wondering: what if muxrpc would support transform streams instead? I have vague memories of wanting that for something in the past. `blobs.add` then could _transform_ the data stream into a hash and this pattern might be more useful in general than a sink with callback?

**Comment by dominictarr** [comment]
@regular that's essentially how it would work internally. really muxrpc only has duplex stream, but it lets you turn off one side (except for errors) to make a source or sink stream. `blobs.add` would be a stream with just one chunk of data (the hash) coming back...

although, I do think it's important that the data coming back can mean the source has succeeded, which is what a cb is for...

hmm, idea: what if you implemented this entirely in user space? and exposed it as duplex? it doesn't seem that hard to do it that way. (hard part is wrangling all the muxrpc tests...) so maybe it isn't that hard.

**Comment by christianbundy** [comment]
Is this still active and/or ready for review?

**Comment by clehner** [comment]
Merged. Thanks @regular.

**Pull request merged**
