### PR TITLE
Add callback parameter which allows client to know when scuttlebot has fully initialised

### PR DESCRIPTION
**Pull request by Happy0**
This change allows some race conditions to be avoided where actions fail because multiserver modules haven't fully initialised.

See the %Y9toy+J+sFmjIPajShEi/6md4FEe54IxN4gxuCry9nU=.sha256 thread on scuttlebutt for more context.

### CODE REVIEW

**Comment by staltz** [comment]
Looks good, but reminder: pending on https://github.com/ssbc/secret-stack/pull/32 and https://github.com/ssbc/multiserver/pull/36

**Comment by dominictarr** [comment]
hmm, I get this error: 
```
G5JYaWqa1w=
Error: Could not connect to ssb-server localhost:undefined
Use the "start" command to start it.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/dominic/c/scuttlebot/bin.js getAddress device -- --host=127.0.0.1 --port=9001 --path /tmp/ssbServer_binjstest_1547077233964 --caps.shs w6dVZWk9lv080WxP7wvYOfs9mqf5RrTM/G5JYaWqa1w=' }

```

**Comment by Happy0** [comment]
@dominictarr - huh. Do you gfet that error when you run `npm start` in the `ssb-server` directory? Or do you get it in some other circumstance?

I'm actually getting another mysterious error when I run `npm start` now:

```
happy0@geogaddi:~/projects/ssb-server$ npm start

> ssb-server@13.5.2 start /home/happy0/projects/ssb-server
> node bin server

WARNING-DEPRECATION: `sbot server` has been renamed to `ssb-server start`
ssb-server 13.5.2 /home/happy0/.ssb logging.level:notice
my key ID: RJ09Kfs3neEZPrbpbWVDxkN92x9moe3aPusOMOc4S2I=.ed25519
Hullo~
WARNING-DEPRECATION: ssb-links not installed as a plugin. If you are using git-ssb, ssb-npm or patchfoo please consider installing it
Listening on undefined:8008 (multiserver net plugin)
Listening on :8989 (multiserver ws plugin)
ssb-friends: stream legacy api used
/home/happy0/projects/ssb-server/node_modules/ssb-db/minimal.js:220
    const isEmptyInactiveQueue = !queue.buffer.queue.length && !queue.writing
                                               ^

TypeError: Cannot read property 'queue' of undefined
    at EventEmitter.db.flush (/home/happy0/projects/ssb-server/node_modules/ssb-db/minimal.js:220:48)
    at /home/happy0/projects/ssb-server/node_modules/ssb-db/index.js:129:12
    at /home/happy0/projects/ssb-server/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/happy0/projects/ssb-server/node_modules/pull-stream/throughs/async-map.js:28:19
    at /home/happy0/projects/ssb-server/node_modules/pull-stream/throughs/through.js:19:9
    at PacketStreamSubstream.weird.read (/home/happy0/projects/ssb-server/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/happy0/projects/ssb-server/node_modules/packet-stream/index.js:200:12)
    at PacketStream.write (/home/happy0/projects/ssb-server/node_modules/packet-stream/index.js:135:41)
    at /home/happy0/projects/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
    at /home/happy0/projects/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37
```

(On the master branch too.) Do you recognise that?

**Comment by dominictarr** [comment]
oh it was a problem with [ssb-config](https://github.com/ssbc/ssb-config/commit/30ae00b4711a8bd65a51beaf2c06d9f61a3caebe#r31890604), it's all fixed now! merged into 13.6.0!

**Comment by Happy0** [comment]
Cheers @dominictarr . I think the package.json file is referencing GitHub commits (same in the secret-stack merge). I'll fix those tomorrow :)

**Comment by dominictarr** [comment]
@Happy0 I already fixed those, so no need.

**Pull request merged**
